=== MIT-STARLab/circinus_orbit_propagation/crux/config/orbit_prop_inputs.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Orbit prop data params",
    "description": "schema for params for that are used as inputs by the orbit propagation routines, including scenario timeframe, satellite orbits, and ground station configuration",
    "type": "object",
    "properties": {
        "version": {
            "description": "version specifier to inform parsing in code. semantics: Major.Minor",
            "type": "string",
            "enum": ["0.1"]
        },
        "num_satellites": {"type": "integer"},
        "scenario_time_params": {
            "type": "object",
            "properties": {
                "start_utc": {
                    "type": "string",
                    "description": "epoch time at which the orbital parameters are valid",
                    "default" : "2018-01-18T11:39:50.52Z"
                }
            }
        },
        "orbit_params": { 
            "oneOf": [
                {"kepler_meananom": {"$ref": "schema_orbit_params.json#/properties/kepler_meananom"}}
            ]
        },
        "gs_params": {}
    }
}

=== MIT-STARLab/circinus_orbit_propagation/crux/config/examples/orbit_prop_inputs_ex.json
{
    "version": "0.1",
    "num_satellites": 20,
    "scenario_time_params": {
        "start_utc": "2018-01-18T11:39:50.52Z"
    },
    "orbit_params": { 
        "kepler_meananom": {
            "propagation_method": "matlab_delkep",
            "a_km":  6978,
            "e": 0,
            "i_deg": 0,
            "RAAN_deg": 0,
            "arg_per_deg": 0,
            "M": 0
        }
    },
    "gs_params": {}
}
